version: '3.8'
services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: "BEALUX_MYSQL"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root@12345
      MYSQL_DATABASE: bealux_mysql
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
