version: '3.9'
services:
  db:
    restart: always
    image: mysql:8.0
    container_name: "BEALUX_DB"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root@12345
      MYSQL_DATABASE: bealux_db
    volumes:
      - db:/var/lib/mysql
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: "BEALUX_API"
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    environment:
      MYSQL_NAME: bealux_mysql
      MYSQL_USER: bealux
      MYSQL_PASSWORD: bealux
    depends_on:
      - db
volumes:
  db:
